num_servers,avg_processing_rate,total_gpus,error
8,19.728571428571428,32,
16,51.896875,64,
32,94.238,128,
64,161.47961538461539,256,
128,211.33043478260868,512,
256,0.0,1024,"Server emulator process died during benchmark:
Got error produce response: [Error 7] RequestTimedOutError Traceback (most recent call last): File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 144, in <module> asyncio.run(main()) File ""/home/tejas/miniforge3/lib/python3.12/asyncio/runners.py"", line 194, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/asyncio/runners.py"", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/asyncio/base_events.py"", line 687, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 139, in main await asyncio.gather(*tasks) File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 128, in run_server await producer.send_metric(metric) File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/producer.py"", line 17, in send_metric await self.producer.send_and_wait(KAFKA_TOPIC, metric_data.encode('utf-8')) File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/producer.py"", line 545, in send_and_wait future = await self.send(topic, value, key, partition, timestamp_ms, headers) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/producer.py"", line 525, in send fut = await self._message_accumulator.add_message( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/message_accumulator.py"", line 417, in add_message raise KafkaTimeoutError() aiokafka.errors.KafkaTimeoutError: KafkaTimeoutError"
512,0.0,2048,"Server emulator process died during benchmark:
Traceback (most recent call last): File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 144, in <module> asyncio.run(main()) File ""/home/tejas/miniforge3/lib/python3.12/asyncio/runners.py"", line 194, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/asyncio/runners.py"", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/asyncio/base_events.py"", line 687, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 139, in main await asyncio.gather(*tasks) File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 128, in run_server await producer.send_metric(metric) File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/producer.py"", line 17, in send_metric await self.producer.send_and_wait(KAFKA_TOPIC, metric_data.encode('utf-8')) File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/producer.py"", line 545, in send_and_wait future = await self.send(topic, value, key, partition, timestamp_ms, headers) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/producer.py"", line 525, in send fut = await self._message_accumulator.add_message( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/message_accumulator.py"", line 417, in add_message raise KafkaTimeoutError() aiokafka.errors.KafkaTimeoutError: KafkaTimeoutError"
1024,0.0,4096,"Server emulator process died during benchmark:
Got error produce response: [Error 7] RequestTimedOutError Traceback (most recent call last): File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 144, in <module> asyncio.run(main()) File ""/home/tejas/miniforge3/lib/python3.12/asyncio/runners.py"", line 194, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/asyncio/runners.py"", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/asyncio/base_events.py"", line 687, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 139, in main await asyncio.gather(*tasks) File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 128, in run_server await producer.send_metric(metric) File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/producer.py"", line 17, in send_metric await self.producer.send_and_wait(KAFKA_TOPIC, metric_data.encode('utf-8')) File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/producer.py"", line 545, in send_and_wait future = await self.send(topic, value, key, partition, timestamp_ms, headers) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/producer.py"", line 525, in send fut = await self._message_accumulator.add_message( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/message_accumulator.py"", line 417, in add_message raise KafkaTimeoutError() aiokafka.errors.KafkaTimeoutError: KafkaTimeoutError"
2048,0.0,8192,"Server emulator process died during benchmark:
Got error produce response: [Error 7] RequestTimedOutError Got error produce response: [Error 7] RequestTimedOutError Unable to request metadata from node with id 1003: KafkaConnectionError('Connection at 10.180.8.24:9093 closed') Traceback (most recent call last): File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 144, in <module> asyncio.run(main()) File ""/home/tejas/miniforge3/lib/python3.12/asyncio/runners.py"", line 194, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/asyncio/runners.py"", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/asyncio/base_events.py"", line 687, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 139, in main await asyncio.gather(*tasks) File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 128, in run_server await producer.send_metric(metric) File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/producer.py"", line 17, in send_metric await self.producer.send_and_wait(KAFKA_TOPIC, metric_data.encode('utf-8')) File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/producer.py"", line 545, in send_and_wait future = await self.send(topic, value, key, partition, timestamp_ms, headers) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/producer.py"", line 525, in send fut = await self._message_accumulator.add_message( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/message_accumulator.py"", line 417, in add_message raise KafkaTimeoutError() aiokafka.errors.KafkaTimeoutError: KafkaTimeoutError"
4096,0.0,16384,"Server emulator process died during benchmark:
Got error produce response: [Error 7] RequestTimedOutError Traceback (most recent call last): File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 144, in <module> asyncio.run(main()) File ""/home/tejas/miniforge3/lib/python3.12/asyncio/runners.py"", line 194, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/asyncio/runners.py"", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/asyncio/base_events.py"", line 687, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 139, in main await asyncio.gather(*tasks) File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 128, in run_server await producer.send_metric(metric) File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/producer.py"", line 17, in send_metric await self.producer.send_and_wait(KAFKA_TOPIC, metric_data.encode('utf-8')) File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/producer.py"", line 545, in send_and_wait future = await self.send(topic, value, key, partition, timestamp_ms, headers) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/producer.py"", line 525, in send fut = await self._message_accumulator.add_message( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/message_accumulator.py"", line 417, in add_message raise KafkaTimeoutError() aiokafka.errors.KafkaTimeoutError: KafkaTimeoutError"
8192,0.0,32768,"Server emulator process died during benchmark:
Traceback (most recent call last): File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 144, in <module> asyncio.run(main()) File ""/home/tejas/miniforge3/lib/python3.12/asyncio/runners.py"", line 194, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/asyncio/runners.py"", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/asyncio/base_events.py"", line 687, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 139, in main await asyncio.gather(*tasks) File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/server_emulator.py"", line 128, in run_server await producer.send_metric(metric) File ""/mnt/c/Users/tejasv/Documents/ExaODAF/dcgm-kafka-simulator-bench/producer.py"", line 17, in send_metric await self.producer.send_and_wait(KAFKA_TOPIC, metric_data.encode('utf-8')) File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/producer.py"", line 545, in send_and_wait future = await self.send(topic, value, key, partition, timestamp_ms, headers) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/producer.py"", line 525, in send fut = await self._message_accumulator.add_message( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/home/tejas/miniforge3/lib/python3.12/site-packages/aiokafka/producer/message_accumulator.py"", line 417, in add_message raise KafkaTimeoutError() aiokafka.errors.KafkaTimeoutError: KafkaTimeoutError"
